version: "3.9"

networks:
  my-network:
    driver: bridge

services:
  app:
    image: hashicorp/http-echo:1.0
    container_name: app
    command: ["-listen=:5000", "-text=Hello from app"]
    expose:
      - "5000"
    networks:
      - my-network

  nginx:
    image: nginx:1.27-alpine
    container_name: nginx
    depends_on:
      - app
    ports:
      - "5001:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs:/etc/nginx/ssl:ro
    networks:
      - my-network

