version: "3.9"

networks:
  my-network:
    driver: bridge

services:
  app:
    image: mcr.microsoft.com/dotnet/aspnet
    container_name: app
    networks:
      - my-network
    expose:
      - "5000"
    environment:
      - ASPNETCORE_URLS=http://0.0.0.0:5000


  nginx:
    image: nginx:1.27-alpine
    container_name: nginx
    depends_on:
      - app
    ports:
      - "5001:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs:/etc/nginx/ssl:ro
    networks:
      - my-network

